ENT.Type = "anim"
ENT.Base = 'base_anim'
ENT.PrintName = "Gate Terminal"
ENT.Author = ""
ENT.Contact = ""
ENT.Purpose = ""
ENT.Category = "За Фрименом"
ENT.Instructions = ""
ENT.Spawnable = true
ENT.AdminOnly	= true